#
# $Id$
# 
# Simple Clean for this sub directory
#
# Note: you can also use the 'Clean' script
#
# This one is a lite version
#

all:

clean:
	@echo " cleaning : bochs/toolkit directory"
	rm -f *~ *.o
	rm -f tmp/orange.img
	rm -f bochs/orange.img
	rm -f vmlinuz vmlinux
	rm -f bochs/bochsout.txt
	rm -f ImageReport.txt

#
# End of Makefile
#
