#----------------------------------------------------------
# Root Makefile for ProjectAkita Operating System
#
# Copyright (c) 2005 - Berlin Brown
#
# berlin.brown@gmail.com
#
#----------------------------------------------------------

all: bochs

backup:
	$(MAKE) -C src backup

bochs:
	$(MAKE) -C src bochs

clean:
	$(MAKE) -C src clean

#----------------------------------------------------------
#
# End of Makefile
#
#----------------------------------------------------------
