#!/bin/sh
#
# Berlin Brown
# Script to remove backup files
# find (cur_dir) -name wildcard [option:type] regular_file
# 		and print with newline
#

echo "INFO: Removing the (garbage/backup) *~ files..."
find . -name '*~' -type f -print \
	| xargs rm -f -v
echo "INFO: done"


