#
# $Id$
#
# Simple Makefile for the java Project
#

all:

.PHONY: clean build

## Make sure to delete the java build directory
clean:
	@echo " cleaning : toolkit/java directory"	
	rm -Rf build
	rm -f *~ *.o
