#
# $Id$
#
# boot - Makefile
#
all:

.PHONY: bootsect boot

#
# Clean up the garbage including GCC generated ASM files *.s
#
clean:
	@echo " cleaning : boot"
	rm -f bootsect
	rm -f setup setup.s mini
	rm -f vmlinux _tmp_*
	rm -f *.o *.s *~